### ISSUE TITLE
Roadmap listing or keep the simplicity likes the current state

### ISSUE THREAD

**Issue by QiProject** [hajimehoshi/ebiten#1206]
Great work, thank you, it seems the only functional go game engine to 
support cross-platform, AT, is any roadmap listing, maybe this could encourage
people to contribute some features, or the authors prefers keep 
the current engine simplicity ?

**Comment by hajimehoshi** [comment]
Hi,

No concrete roadmap so far yet, but my vague plan is:

* Nov 2020: Shaders
  * Now I'm working on this.
* 2020?: Porting to Nintendo Switch
  * I have developed [go2cpp](https://github.com/hajimehoshi/go2cpp) to support environments where Go doesn't support. Unfortunately, because of NDA, I cannot say the details even if I have succeeded to run Ebiten applications on Switch. However, I believe supporting Switch would be feasible.
* Mar? 2021: Ebiten v2
  * No drastic change. I'd like to add some API change and remove already-deprecated features.
* 2021?: Vector graphics
  * Now there is [vector](https://pkg.go.dev/github.com/hajimehoshi/ebiten/vector?tab=doc) package, but I need to add more features.

That's it. I'd like to keep the current engine simplicity. Especially after supporting shaders and vector graphics, there is no plan to add big features. Non-visible change like supporting more platforms (e.g., Raspberry Pi Zero by Dispman, ARM Windows by using DirectX, etc) will be more important. Even if we don't add big changes, there are a lot of things to do.

Contributions are always welcome!

**Comment by QiProject** [comment]
Thanks for the detailed info.
Maybe this could go in readme.md since you already have typed it :D
I am doing more aiming to mobile platforms, so I am glad to have the actual
Ebiten support.

I am happy that vector is in the list, I miss those days that you could draw
interesting things via drawing api in flash.

Sure, I will see I would be able to contribute some, after I finish my first game with Ebiten!

**Comment by hajimehoshi** [comment]
> Maybe this could go in readme.md since you already have typed it :D

Thanks, but I think I'd write a blog article, as I'd like to keep README as simple as possible.

I appreciate all your Ebiten usages, feedbacks and contributions!

**Comment by hajimehoshi** [comment]
https://ebiten.org/blog/roadmap2020.html Brushed up the roadmap
