### ISSUE TITLE
gomobile: no Android NDK found in $ANDROID_HOME/ndk-bundle nor in $ANDROID_NDK_HOME

### ISSUE THREAD

**Issue by zladnrms** [hajimehoshi/ebiten#1318]
Hello. 

My $ANDROID_HOME = /Users/kim/Library/Android/sdk
and  $ANDROID_NDK_HOME = /Users/kim/Library/Android/sdk/ndk/21.2.6472646

And just in case, i mkdir **ndk-bundle** folder in /Users/kim/Library/Android/sdk ,
so i have /Users/kim/Library/Android/sdk/ndk-bundle/21.2.6472646 , too.

but ebitenmobile  command always invoked error likes below.
<img width="571" alt="스크린샷 2020-08-21 오전 4 23 24" src="https://user-images.githubusercontent.com/13454523/90815698-0f3c4980-e366-11ea-80be-ce6287b4de0f.png">
_upper image's pwd = /Users/kim/go/bin_

i don't know why ebitenmobile command doesn't recognize my ndk folder settings

**and one more question.**
in ebiten mobile guide's part. 

`ebitenmobile bind -target android -javapkg [your.domain] -o [path/to/yourgame.aar] `

what is your.domain?    it likes a "yahoo.com"? 

thanks for reading! please !

**Comment by tomlister** [comment]
Hi zladnrms,

**NDK**
In my case I had to install NDK 19.2.5345600 due to incompatibilities with ndk versions greater than 20.x.x https://github.com/golang/go/issues/35030
Don't forget to create an alias called /ndk-bundle/ to /ndk/19.2.5345600/

**Domain**
`your.domain` should be formatted in [reverse domain name notation.](https://en.wikipedia.org/wiki/Reverse_domain_name_notation)
For example: `tld.domain.subdomain` or `com.github.tomlister`
In your case it would be `com.github.zladnrms`

Regards,
Tom.

**Comment by hajimehoshi** [comment]
Let me close this.
