### ISSUE TITLE
clock: Test with 60> Hz display

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1445]
Probably Ebiten doesn't work as expected with a 120 or 144 Hz display. Test them.

**Comment by Zyko0** [comment]
May I help testing something ? 240hz display here

**Comment by hajimehoshi** [comment]
Thanks! Do Ebiten applications (especially examples/window) work on your display?

**Comment by Zyko0** [comment]
Yes it definitely works on my own project (playing with shaders atm), I'm also on windows btw !
I just ran your `example/windowsize`, played a bit with TPS/vsync and everything looks smooth

I know it works fine because using interpolation for drawing in my own projects let me have a tps of 30/60/120 still with a smooth 240-3k+ fps.

In this example, TPS regulate FPS as well, so I can't see it showing extra frames since it's just faster in `uncapped` tps mode

**Comment by hajimehoshi** [comment]
Thank you for confirming that!
