### ISSUE TITLE
graphicscommand: Use structs instead of interfaces for each command

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1475]
![image](https://user-images.githubusercontent.com/16950/106353624-40ff0680-632f-11eb-8b10-b1acaac4048a.png)

(Ebiten 44bb004cb78210dda3ead32936ce373f5ec5043e)

`EnqueueDrawTrianglesCommand` is one of the most significant caller of `runtime.mallocgc`. This allocates `drawTrianglesCommand` objects on the heap. We can avoid allocating them on the heap, but this requires some amount of works. For example, we should avoid interfaces for commands in order to avoid pointers for `commands` slice, probably.

**Comment by Zyko0** [comment]
As long as objects have references (e.g in `drawTrianglesHistory` slices for example), they will always be allocated on the heap am I wrong ?

Maybe you could share `drawTrianglesCmd` definition with both (they look very similar) https://github.com/hajimehoshi/ebiten/blob/44bb004cb78210dda3ead32936ce373f5ec5043e/internal/restorable/image.go#L408-L422
and
https://github.com/hajimehoshi/ebiten/blob/44bb004cb78210dda3ead32936ce373f5ec5043e/internal/graphicscommand/command.go#L177-L192

So that the same reference to the cmd item would be manipulated by both parts, it helps if the structure only contains definition and getters obviously (and is not being written to by any part).
This would save some extra allocations by reducing command copies, but might change the design you look for (?)

Also, would a pre-allocation of `q.commands`, `drawTrianglesHistory` slices to a max length (or at least capacity) would help ? (with care to some noncomputer-devices' memory)
With a bit of:
```go
// add (works with commands too obv)
drawTrianglesHistory = drawTrianglesHistory[:len(drawTrianglesHistory)+1]
drawTrianglesHistory[len(drawTrianglesHistory)-1] = newCmd
```
and
```go
// del
drawTrianglesHistory[len(drawTrianglesHistory)-1] = nil
drawTrianglesHistory = drawTrianglesHistory[:len(drawTrianglesHistory)-1]
```

Btw reducing usage of pointers might instantiate extra structures by copy, which would reduce malloc calls but might create another issue :/

Sorry for not saying specific stuff, neither suggesting direct solutions, tho I hope it helps you getting other ideas on how to handle this issue 😅

**Comment by hajimehoshi** [comment]
> As long as objects have references (e.g in drawTrianglesHistory slices for example), they will always be allocated on the heap am I wrong ?

This depends on whether the environment requires restoring from context-lost or not. Now we assume that context lost happens only on Android and browsers so far.

> Maybe you could share drawTrianglesCmd definition with both (they look very similar)

Yeah but this is not an obvious tasks, and actually they are slightly different. Besides, I'd like to remove the restorable side in the not-near future, so I don't plan to merge them so far.

> Also, would a pre-allocation of q.commands, drawTrianglesHistory slices to a max length (or at least capacity) help ? (with care to some noncomputer-devices' memory)

My understanding is `append` is already enough as long as they have enough capacity, and the capacity should remain until the underlying array is gone. So we don't have to modify the current logic.

> Btw reducing usage of pointers might instantiate extra structures by copy, which would reduce malloc calls but might create another slowdown

`drawTrianglesCommand` doesn't copy elements (or we can remove copyings if necessary) so I think this should not matter.

> Sorry for not saying specific stuff, neither suggesting direct solutions, tho I hope it helps you getting other ideas on how to handle this issue 😅

No problem, thank you for the suggestions!

**Comment by Zyko0** [comment]
Thanks for your explanations !

> This depends on whether the environment requires restoring from context-lost or not. Now we assume that context lost happens only on Android and browsers so far.

Yeah I meant that I couldn't see how the commands/history slices would ever be on the stack, since they are being flushed by other methods

> My understanding is append is already enough as long as they have enough capacity, and the capacity should remain until the underlying array is gone. So we don't have to modify the current logic.

That is true, but as slices have a 0 capacity at first, I was wondering if your screenshot was taken at the beginning of your application. Which would lead to a lot of resizing of the underlying array for each new cmd/historyitem at start (allocating bigger array and copying the previous one to the new one).

> `drawTrianglesCommand` doesn't copy elements (or we can remove copyings if necessary) so I think this should not matter.

Yes it doesn't matter actually, I meant when arrays (not slice) are passed by value to functions, idk why I mentioned that.

**Comment by hajimehoshi** [comment]
Hmm, I forgot the context. The heaviest task in mallocgc depends on games. Let's revisit this later...
