### ISSUE TITLE
Is `DrawTrianglesOptions` missing a `GeoM`?

### ISSUE THREAD

**Issue by ajzaff** [hajimehoshi/ebiten#1806]
_This may be filed under the tag of questions but I am interested in the change if feasible._

I would like to draw object meshes using the `DrawTriangles*` API. Without a GeoM however, I must compute `vertices+geoM` every update. Have I misused the API or is this working as intended? Is there some technical reason why we cannot pass a `GeoM` for these Draw calls.

Thanks!

**Comment by hajimehoshi** [comment]
Right, `DrawTrianglesOptions` doesn't have `GeoM` and you have to adjust vertices by yourself. Actually with `GeoM`, the calculation happens every update inside.

> Is there some technical reason why we cannot pass a GeoM for these Draw calls.

No technically reason. It's just because 1) `DrawTriangles` users should have more controls of vertices than `DrawImage`, then I thought we don't have to have it and 2) performance. If `GeoM` exists in the option, performance is a little degraded due to some overhead.
