### ISSUE TITLE
internal/graphicsdriver/directx: improve vsync-off performance with DirectX

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2034]
Even when vsync is disabled, the DirectX doesn't get a very high FPS compared to OpenGL. It's because all the resources waits for the rendering the current implementation, which might not be needed.

**Comment by divVerent** [comment]
FYI because of this, I have temporarily disabled the DirectX backend in my game when building against Ebiten main (by forcing the environment variable to set the backend unless it is already set, essentially changing its default while preserving the ability to override it): I have worse performance than GL with and without vsync.

Now these resource waits may be a hint to why this is; so nice finding here!

**Comment by hajimehoshi** [comment]
I think this is reported by @Zyko0. Could you try a32a137fa805f8dca08e499a85f6e84fb96361c8? Thanks,

**Comment by hajimehoshi** [comment]
I found a new thing: https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/variable-refresh-rate-displays

**Comment by Zyko0** [comment]
> I think this is reported by @Zyko0. Could you try `a32a137f`

I just tried `v2.4.0-alpha.9` since you pushed on that one too, and there's definitely an improvement!
I'm no longer stuck to a fixed value, I reached 950~ with directx on https://github.com/Zyko0/GameOff2021 main menu vs 3200+ with opengl

Now I can tell I'm not stuck to a magic number anymore on any of my projects, so it "just" looks slower than opengl based on `ebiten.CurrentFPS()`. But I can't really tell visually anyway, if ever the resulting "fps" value from this method is biased depending on the graphic driver

🚀

**Comment by hajimehoshi** [comment]
OK so there is still a magic in the OpenGL driver, but an actual issue was resolved.

Thank you for confirming this! Let me close this.
