### ISSUE TITLE
ebiten: clean up APIs for TPS

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2071]
* Renaming (= adding an alias for) `SetMaxTPS` -> `SetTargetTPS` or `SetTPS`
* Renaming or removing `CurrentTPS`

I have not decided yet...

**Comment by themowski** [comment]
For the record, I prefer `SetTargetTPS` because it is more self-documenting -- it conveys that the value being set is a target, not necessarily the exact value that will show up in practice at all times. `SetTPS` seems more "absolute" to me, like it is guaranteeing that TPS value will be used, and it will never go (very far) below/above that. Although based on the discussion in Discord, it sounds like that is actually the case, unless application logic prevents the Update loop from finishing in time... so in the end, this might come down to the author's preference. 😉 

Regardless of the name though, I think good documentation explaining the concept of TPS (along the lines of what we have been discussing in Discord), put either directly in the docstring for the method or in an article that is then linked to by the docstring for the method, would be very effective in curbing confusion moving forward.

**Comment by tinne26** [comment]
Following up the discussion on the `SetTargetTPS` name: my only concern is that "target" is a very overloaded term that can also lead to confusion as is often used to refer to devices and specific elements. This is very subjective, though. The right word would indeed be in the nebula of ("pursued", "target", "ideal", "theoretical", "normal"), but *none* of those sound exactly right to me... which makes me lean more towards `SetTPS`.

**Comment by Zyko0** [comment]
> which makes me lean more towards SetTPS

Same, if I have a function to set the max tps, I am then looking for a function to set the actual tps, and not a maximal limit.
Otherwise, it makes me believe that it could be common for it not to be reached (actually what happened when I discovered ebiten)

**Comment by hajimehoshi** [comment]
* I'll add an alias `SetTPS` for `SetMaxTPS`.
* I'll leave `CurrentTPS` as it is (I forgot the current issue around `CurrentTPS`... Probably some people tried to use it for their logics?)

**Comment by hajimehoshi** [comment]
Ah, the getter `MaxTPS` will be `TPS`. Then `CurrentTPS` would be confusing. Probably `ActualTPS` might be better.

**Comment by hajimehoshi** [comment]
Hmm, ActualFPS seems a little odd... 🤔

**Comment by hajimehoshi** [comment]
@themowski @tinne26 @Zyko0 What do you think about my plan https://github.com/hajimehoshi/ebiten/issues/2071#issuecomment-1181264006 ?

**Comment by tinne26** [comment]
Agree that `ActualTPS` is not a great name, and whatever it's chosen should probably also be reflected for `CurrentFPS` for consistency. Everything else seems good.

But I also can't find the right word. `MeasureTPS` / `MeasureFPS` don't sound quite right either. They are less confusing than `CurrentTPS` and `CurrentFPS`, but it sounds as if you are actively doing something to check them right now, when actually they are always being monitored. Monitor, inspect, measure... hmm, nothing sounds good. Other ideas could be `GetTPSPerformance` or similar, but that's also quite long and not necessarily clear. Anyone else has better ideas?

**Comment by hajimehoshi** [comment]
> Agree that ActualTPS and ActualFPS are not great names,

IMO ActualTPS is not so bad but ActualFPS seems odd :-)

**Comment by SolarLune** [comment]
AverageTPS() and AverageFPS() could work - that gives the idea that they're averaged out current values.

**Comment by hajimehoshi** [comment]
I see, so

* `SetMaxTPS()` -> `SetTPS()`
* `MaxTPS()` -> `TPS()`
* `CurrentTPS()` -> `AverageTPS()`
* `CurrentFPS()` -> `AverageFPS()`

seems nice. Or, what about

* `SetMaxTPS()` -> `SetTPS()`
* `MaxTPS()` -> `TPS()`
* `CurrentTPS()` -> `MeasureTPS()`
* `CurrentFPS()` -> `MeasureFPS()`

?

**Comment by SolarLune** [comment]
Either is fine from my point of view~

**Comment by hajimehoshi** [comment]
I think I'll go with `Actual`. Then the plan is:

* `SetMaxTPS()` -> `SetTPS()`
* `MaxTPS()` -> `TPS()`
* `CurrentTPS()` -> `ActualTPS()`
* `CurrentFPS()` -> `ActualFPS()`
