### ISSUE TITLE
ebiten: add an API to set graphics engine programmatically 

### ISSUE THREAD

**Issue by erexo** [hajimehoshi/ebiten#2094]
As of Ebiten [2.3.0](https://ebiten.org/documents/2.3.html#An_environment_variable_EBITEN_GRAPHICS_LIBRARY) we are able to choose graphics library via environment variable. This may be a little cumbersome because programmers must be aware of available libraries for currently used OS, of their string representations as env variable and most importantly must deal with the env variables in their games which may be cumbersome.
My proposal is explained in correlated [PR](https://github.com/hajimehoshi/ebiten/pull/2093). My motivation is also dictated by the fact, that there are already API functions that are only available before game launch, such as `SetInitFocused`, so `SetGraphicsEngine` would naturally fit in current system.

**Comment by Erexo** [comment]
I can, but why would I want to do that instead of executing a dedicated API function? Why do we want to have multiple ways to interact with the game before launch? 
Why
`os.Setenv("EBITEN_GRAPHICS_LIBRARY", "opengl")
ebiten.SetInitFocused(true)
ebiten.RunGame(g)`
is better than
`ebiten.SetGraphicsEngine(ebiten.GraphicsEngineOpenGL)
ebiten.SetInitFocused(true)
ebiten.RunGame(g)`
?

**Comment by hajimehoshi** [comment]
> Why do we want to have multiple ways to interact with the game before launch?

My policy is to keep Ebiten simple and I don't want to provide multiple ways for the same thing whenever possible.

**Comment by Erexo** [comment]
> My policy is to keep Ebiten simple and I don't want to provide multiple ways for the same thing whenever possible.

And thus we set some functions via env variables, and others via API functions to the library 😄

**Comment by hajimehoshi** [comment]
I don't see your point...

In the first place, why do you want to switch the graphics library?

**Comment by Erexo** [comment]
>In the first place, why do you want to switch the graphics library? This should be pretty rare.
If there is no point in switching the graphics library, why did you add that option to the Ebiten in the first place?

I do have cases when players willingly want to switch to OpenGL while on Windows due to performance issues. It is rare but it does not mean that it doesn't appear and I shouldn't address those issues. So right now I can hardcode the strings for available libraries and deal with the OS' environment variables, but I thought that it should be as easy as deciding if the window should be focused at start or not.

**Comment by hajimehoshi** [comment]
> If there is no point in switching the graphics library, why did you add that option to the Ebiten in the first place?

There are some rare cases when they find a rendering issue in DirectX for example.

> I do have cases when players willingly want to switch to OpenGL while on Windows due to performance issues. It is rare but it does not mean that it doesn't appear and I shouldn't address those issues. So right now I can hardcode the strings for available libraries and deal with the OS' environment variables, but I thought that it should be as easy as deciding if the window should be focused at start or not.

Yeah actually this is the case, but I still don't think we really need to offer an easy way to do so.

**Comment by Erexo** [comment]
> There are some rare cases when they find a rendering issue in DirectX for example.

Exactly 😄

> but I still don't think we really need to offer an easier way to do so than the environment variable

Sure thing, it is your call, I've just made an offer 😀

**Comment by hajimehoshi** [comment]
Let me leave this issue open.

**Comment by hajimehoshi** [comment]
Let me integrate this into #2378
