### ISSUE TITLE
OBS doesn't list an Ebitengine's game

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2148]
https://obsproject.com/

The reported environment was Windows.

**Comment by sinisterstuf** [comment]
This works fine on Linux btw, and whether the Windows are capturable or not in OBS here depends on whether you have software available to capture them, which differs whether you are using X11 or Wayland. This doesn't really help debugging this on Windows, but what I'm trying to say is that the issue might be with OBS, not Ebitengine. Or the bug is very platform specific.

**Comment by hajimehoshi** [comment]
Apparently, when OpenGL is used, OBS requires an additional option `--allow-opengl`. I guess this is the problem.

I hope #2613 would mitigate the issue.

**Comment by hajimehoshi** [comment]
As #2613 uses DirectX (11), I'll close this and revisit when needed.
