### ISSUE TITLE
ebiten: API to get the current graphics library

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2177]

**Comment by RusAD32** [comment]
My idea is to add a method to `UserInterface` type (in `internal/ui/ui,go`) that goes something like this
```
func (u *UserInterface) getGraphicsDriverName() string {
	if u.graphicsDriver.IsGL() {
		return "opengl"
	} else if u.graphicsDriver.IsDirectX() {
		return "directx"
	} else {
		return "metal"
	}
}
```
and add a public function somewhere that will call this method somewhere (`window.go`?) that wraps it and can be called from outside. 

If this looks good, I can create a pull request, otherwise let's discuss how to best do this?

**Comment by hajimehoshi** [comment]
Thanks. So rather than an implementation, I'd like to determine the public API first. As this is one of a debug information,

```go
type GraphicsLibrary int

const (
    GraphicsLibraryUnknown
    GraphicsLibraryOpenGL
    ...
)

type DebugInfo struct {
    GraphicsLibrary GraphicsLibrary
}

func ReadDebugInfo(*DebugInfo)
```

might be good but I'm not 100% sure. Perhaps this should be in `ebitenutil` rather than `ebiten`. Let me think more...

**Comment by hajimehoshi** [comment]
> u.graphicsDriver.IsGL()
> u.graphicsDriver.IsDirectX()

Hm, I don't want to use these API to be honest as I want to remove these in the future... We can record which graphics library is used inside the ui package at the initialization anyway.

**Comment by RusAD32** [comment]
> We can record which graphics library is used inside the ui package at the initialization anyway.

Then it will require changing `graphicsdriver.Graphics` interface in order to retrieve this info, I think. In this case, it's reasonable to remove `IsGl()` and `IsDirectX()` within the scope of this issue as well. 

> Perhaps this should be in ebitenutil rather than ebiten.

There are currently checks for `IsGl()` and `IsDirectX()` in the driver code though. So maybe in `ui`:

```
type GraphicsLibrary int

const (
    GraphicsLibraryUnknown
    GraphicsLibraryOpenGL
    ...
)
type Graphics interface {
   ...
   GetCurrentGraphicsLibrary() GraphicsLibrary
   ...
}
```

and in `ebitenutil` something like 

```

type DebugInfo struct {
    GraphicsLibrary GraphicsLibrary
}

func ReadDebugInfo(*DebugInfo) { ... }

func (d *DebugInfo) GraphicsLibraryToString() string { ... }
```
?

**Comment by hajimehoshi** [comment]
OK let's start with `ebiten` package (not `ebitenutil` package) with this API:

```go
package ebiten

type GraphicsLibrary = ui.GraphicsLibrary

const (
    GraphicsLibraryUnknown = ui.GraphicsLibraryUnknown
    GraphicsLibraryOpenGL = ui.GraphicsLibraryOpenGL
    ...
)

type DebugInfo struct {
    GraphicsLibrary GraphicsLibrary
}

func ReadDebugInfo(*DebugInfo)
```

```go
package ui

type GraphicsLibrary int

const (
    GraphicsLibraryUnknown
    GraphicsLibraryOpenGL
    ...
)
```

1. Fix `(*ui.graphicsDriverCreatorImpl).newAuto` to return a graphics library type. Note that newAuto is defined for various platforms.
2. Fix `ui.newGraphicsDriver()` to save the graphics library type to `ui.globalState`
3. Add `ui.GraphicsLibrary() ` to return the current graphics library type
4. Implement `ebiten.ReadDebugInfo`
