### ISSUE TITLE
ebiten: a new API to skip `Draw` (using the previous framebuffer as it is) for GPU efficiency

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2341]
Forked from https://github.com/hajimehoshi/ebiten/issues/2338.

Especially for UI applications, executing GPU commands every frame is waste of GPU power. Let's provide a way to skip `Draw`.

**Comment by tinne26** [comment]
Summarizing the main three methods proposed to implement this:
- Have a new `SkipDraw()` function that can be called at any time. Pros: most flexible option for the user. Cons: massively harder to implement than the other options (if possible at all without substantial side-effects).
- Return a special `ebiten.SkipDraw` error from `Game.Update() error`. Pros: can easily be composed when other sub-elements also implement `Update() error` methods, and is reasonable to implement. Cons: it's unclear what happens when multiple `Update()`s and / or `Draw()`s are called consecutively: are skips ignored if a later update "overrides" the previous without a draw in between? Are all draws skipped, or only the first? Whatever the answers, these technical details might end up biting users. Using errors for this also looks somewhat ugly to me, but that's just nitpicking (and Golang has done this before with `filepath.SkipDir`, indeed).
- Check the `Game` interface for an optional `SkipDraw() bool` method. Pros: solves the granularity problems that a skip draw error would have, while still being reasonable to implement. Cons: can't be composed like update error returns[^1], adding optional interface methods is not very scalable, and finally in terms of API design it doesn't feel very in line with Ebitengine's style.

Then there's an additional, mostly orthogonal optional performance enhancement:
- Automatically count draws on the main screen `*ebiten.Image`, and when zero, skip buffer swaps anyway. While this seems simple enough, we must keep in mind that `Draw()` should still be called, as it wouldn't be ok to skip that without the user knowing (they could be tracking something on `Draw()` to control performance or similar). I'd be against implementing this, I don't see it necessary, but it's worth mentioning it.

[^1]: I realized this while thinking about UI frameworks. They are often quite opaque and self-managed and you can't touch or inspect the internals, but being able to skip draws is still very important if nothing has changed. Therefore, any Ebitengine UI framework should match the model that Ebitengine itself uses to skip draws. If errors are used, then UI frameworks can return `ebiten.SkipDraw` from their update methods too. Otherwise they probably would use an explicit `SkipDraw()` method on their components. None of the two alternatives are a problem, actually, but errors are more compatibility friendly. In any case, UI frameworks should be kept in mind for this issue quite prioritarily.

**Comment by hajimehoshi** [comment]
Related #2342

**Comment by hajimehoshi** [comment]
> Automatically count draws on the main screen *ebiten.Image, and when zero, skip buffer swaps anyway. While this seems simple enough, we must keep in mind that Draw() should still be called, as it wouldn't be ok to skip that without the user knowing (they could be tracking something on Draw() to control performance or similar). 

But, as Update is still called, do we really care about the cost of Draw here?

**Comment by hajimehoshi** [comment]
The cons of the `skip-if-Draw-does-nothing` way is that a user would have to call `SetScreenClearedEveryFrame(false)`  explicitly.

**Comment by hajimehoshi** [comment]
@tinne26 I found that swapping buffers showed the previous screen state, and this caused a blinking rendering. Now swapping buffers means we don't wait for vsync, so this is not an option.

On the other hand, our purpose is to stop unnecessary rendering for performance, so rendering offscreen every frame is not an option.

Is that correct? I started to double that rendering the (already created) offscreen everyframe would be really costy.

**Comment by hajimehoshi** [comment]
> While this seems simple enough, we must keep in mind that Draw() should still be called, as it wouldn't be ok to skip that without the user knowing (they could be tracking something on Draw() to control performance or similar).

This is not clear to me. SkipDraw would skips Draw calls, so what would be a problem when a user tries to track something on Draw.

Now I think this sounds the best idea as this issue would turn to be just a performance-optimization thing.

**Comment by hajimehoshi** [comment]
Ebitengine now optimzes GPU usages when `SetScreenClearedEveryFrame(false)` and `Draw` doesn't draw anything onto the given screen. The GPU usage cannot be 0% as framebuffers are still swapped, but the usage is pretty low now.

@tinne26 Could you take a look? I'm not sure but this might be already enough optimization in many cases.

**Comment by hajimehoshi** [comment]
In theory, we can do further optimizations: if draw calls for an image are the same in the previous frame, we can skip them automaticallly. However, I feel like the overhead would be significant.

**Comment by tinne26** [comment]
Testing on a laptop with Windows 11, OpenGL seemed to go down from 8% to 3.0-3.5% or so, but for DirectX it wasn't so noticeable, maybe 8% to 6.5-7.0%, harder to tell.

I agree that the overhead of comparing draw calls would be significant. I don't think that optimization would be worth it, and it's not going to help us go from 2-4% to 0% either. I think the current improvements are as far as we can go without skipping buffer swaps or compromising simplicity in the internal implementation.

(That was all. The next comments are only for the sake of discussion and perspective on the topic.)

If we want to continue improving efficiency up to the level of a general desktop app, the remaining options are:
1) Allow manually disabling and later re-enabling buffer swaps, let's say `SuspendSwapBuffers(bool)`.
2) Cut down CPU usage by allowing async input handling, eliminating the dependency on `Update()`.

The first point is very low level and manual, and seems simple to implement but you may not want to expose that on the API (because there's the big issue of burning CPU in a busy loop if the user doesn't manually add sleeps). The second is a big topic that we might be interested in for other reasons, but that doesn't make sense to pursue solely due to the efficiency concerns. None of these seem too reasonable, so barring the implementation of a new main loop mode that's specifically designed around async input and on-demand draw for best efficiency, I wouldn't really suggest anything else. That's an interesting idea, but it definitely falls outside the primary goals of Ebitengine.

All in all, I think this is as far as we should go in this issue.

**Comment by hajimehoshi** [comment]
I see.

> None of these seem too reasonable, so barring the implementation of a new main loop mode that's specifically designed around async input and on-demand draw for best efficiency, I wouldn't really suggest anything else. That's an interesting idea, but it definitely falls outside the primary goals of Ebitengine.

I agree with them. Now we have a simple GPU optimization, the above items might be nice to have. Let me remove the milestone from the issue.

**Comment by hajimehoshi** [comment]
> In theory, we can do further optimizations: if draw calls for an image are the same in the previous frame, we can skip them automaticallly. However, I feel like the overhead would be significant.

By this optimization, GPU usages could be almost 0% on Windows and macOS (and hopefully Linux). I think this is already enough and don't want to add new APIs. Let's close this as 'won't fix' and revisit this later when we find it really needed.
