### ISSUE TITLE
text: redesign APIs to considering sub-pixels

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2469]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

Now one glyph image is cached for one glyph, and they don't consider 'sub-pixel' offsets. Then, whatever the offset is, the same glyph image is always used. The rendering quality is not good.

@tinne26 suggested 'horizontal non-quantized rastering' to use 64 variations of a glyph image. As a glyph image only has alpha channel information, we can use 4 channels for one texture image. Then, as the overhead, the number of images will be increased by 64/4 = 16 times. I think this is reasonable.

See also https://github.com/tinne26/etxt/blob/main/docs/quantization.md

### Why is this needed?

For high-quality text rendering.

**Comment by hajimehoshi** [comment]
OK, updated the title.

**Comment by hajimehoshi** [comment]
> This is more important for text animation and high-resolution horizontal interspacing than overall quality

I meant these are about qualities actually.

**Comment by hajimehoshi** [comment]
Hm, the font [`goregular`](https://pkg.go.dev/golang.org/x/image/font/gofont/goregular) has integer advances and kerns, so subpixels are not available (as long as the start position is an integer)

**Comment by hajimehoshi** [comment]
Same as "M+ font". I'm not sure but `github.com/benoitkugler/textlayout/fonts/truetype` might have a different result.

**Comment by hajimehoshi** [comment]
The current APIs

```
func Draw(dst *ebiten.Image, text string, face font.Face, x, y int, clr color.Color)
func DrawWithOptions(dst *ebiten.Image, text string, face font.Face, ...)
func AppendGlyphs(glyphs []Glyph, face font.Face, text string) []Glyph
```

don't take float positions. Thus, there is nothing we can do with the current API so far...

**Comment by tinne26** [comment]
First: I don't know where you take it from that Go Regular and M+ have integer advances and kerns. All fonts are defined in abstract "units", which are integer values, sure, but when you scale those units to actual sizes, you can absolutely have non-integer advances, kerns and sizes. Anything that can be arbitrarily scaled can end up being non-integer in size. Maybe you are using the `font.Face` `GlyphAdvance()` method instead of the `sfnt.Font` method and leaving the font face hinting to full, which does quantize positions (it should be called quantization and not hinting, because sfnt doesn't do any actual hinting with the hinting data in the font tables... but there are also has bugs in the [computation of kerns](https://github.com/golang/go/issues/46727) and [vertical quantization](https://cs.opensource.google/go/x/image/+/refs/tags/v0.1.0:font/sfnt/sfnt.go;l=1727) anyway, so I didn't have high hopes).

Second: while I agree that it's not feasible to adapt the current APIs to do everything we want them to do without breaking compatibility, the fact that the initial position is an integer position doesn't prevent one from rendering without horizontal quantization. Sure, the first character starts at a quantized position, but the following ones will fall wherever they have to. It's true though that this is an obstacle when it comes to animation, as in most cases you would need to modify the starting position as part of the animation, meaning that you would need to specify the new starting position in fractional pixels.

Third: I don't know what filtering has to do with any of this.

**Comment by hajimehoshi** [comment]
>  I don't know where you take it from that Go Regular and M+ have integer advances and kerns. 

The returned value of `(font.Face).GlyphAdvance` and `(font.Face).Kern` had integer parts.

> Maybe you are using the font.Face GlyphAdvance() method instead of the sfnt.Font method and leaving the font face hinting to full,

I see. I'll try `sfnt.Face` directly then.

> Sure, the first character starts at a quantized position, but the following ones will fall wherever they have to.

Do you assume we should get non-quantized advances?

> Third: I don't know what filtering has to do with any of this.

When you draw an image with a nearest filter, the behavior is like 'quantized'. If you animate an image in X direction with the nearest filter, the rendered image position always takes an integer position.

**Comment by hajimehoshi** [comment]
https://cs.opensource.google/go/x/image/+/refs/tags/v0.1.0:font/sfnt/sfnt.go;l=1630-1633

Aha, so the glyph advances are quantized due to the hinting.

**Comment by tinne26** [comment]
Filtering is not relevant. Even when the glyph position is not quantized, the glyph is drawn on a normal image big enough to contain it, such that when the image is drawn at an integer pixel coordinate, the actual glyph will fall in the appropriate fractional pixel position. It's the glyph renderer's job to take into account the fractional position and adjust the resulting image bounds appropriately. E.g.:
> Returned masks have their coordinates adjusted so the mask is drawn at dot origin (0, 0) + the given fractional position by default.

(from [emask.Rasterize](https://pkg.go.dev/github.com/tinne26/etxt@v0.0.7/emask#Rasterize) docs)

**Comment by hajimehoshi** [comment]
OK we could adjust the glyph images if the API could take float positions.

**Comment by hajimehoshi** [comment]
I confirmed that the given hinting changed the result.

**Comment by hajimehoshi** [comment]
I realized that we don't need 1/64 pixel granularity and 1/4 would be enough. Now the text package should work well with `HintingVertical`.

Before:
![before](https://user-images.githubusercontent.com/16950/203928400-98783688-aacb-4ad3-8295-03e31078593b.png)

After:
![after](https://user-images.githubusercontent.com/16950/203928416-dd84abb5-1b3b-4a0f-bdaa-183139e9ef13.png)

**Comment by tinne26** [comment]
Would have to see if 1/4 is enough for animation, but yeah, still a win. You may consider the same for vertical non-quantization. Also, `HintingNone` *needs horizontal quantization off too* (and vertical quantization off too if you end up supporting that).

**Comment by hajimehoshi** [comment]
Actually I don't target the animation with the current API as the start position is always quantized.

> You may consider the same for vertical non-quantization

I don't think we need this so far. It doesn't seem worth to take 4x more glyph images.
