### ISSUE TITLE
internal/ui: too quick wheel might miss delta information

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2487]
### Ebitengine Version

c12799dc050a24beb1e5e2b3c6f75740f084a480

### Operating System

- [X] Windows
- [X] macOS
- [X] Linux
- [X] FreeBSD
- [X] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.19.2 darwin/amd64

### What steps will reproduce the problem?

Scroll your mouse wheel very quickly.

### What is the expected result?

Accumulated deltas should be reported at one Update for one tick.

### What happens instead?

Only the last delta is reported at one Update for one tick.

### Anything else you feel useful to add?

https://github.com/hajimehoshi/ebiten/blob/84dd1679e3c0ec6eeb7e8077d22ecaf57607be28/internal/ui/input_glfw.go#L174:L179

Reported by @tinne26

**Comment by tinne26** [comment]
While this improves the situation, I don't think it is enough. In particular, multiple reads during `Update()` can still report different values. For example, reading `Wheel()` at the start of the `Update()` method and at the end can return inconsistent values. I don't think this happens for any other kind of input in Ebitengine. Using a separate accumulator for the callbacks that's only swapped during input update could solve this, but it may also slightly increase the wheel latency.

**Comment by hajimehoshi** [comment]
What kind of incosistency are there?

In order to resolve this issue completely, we would need input handling rather than the current Wheel function.

**Comment by tinne26** [comment]
So, `Wheel()` returns the wheel offset since the start of the current update. If the user's `Game` does something like this:
```Golang
func (g *Game) Update() error {
    _, wheelOffsetY1 := ebiten.Wheel()
    time.Sleep(6*time.Millisecond)
    _, wheelOffsetY2 := ebiten.Wheel()
    if wheelOffsetY1 != wheelOffsetY2 {
        panic("different wheel offsets")
    }
}
```
Update will panic, because the results of these calls can change within a single `Update()`.

This is the inconsistency I was talking about. But the main problem is that these inconsistencies can also happen *outside* `Update()`. In fact, they can happen in places completely outside the user's control, which means that those wheel changes will be lost for the user. The user can never detect them with the current implementation.

**Comment by hajimehoshi** [comment]
I see. The same thing can happen with any input APIs as long as they are global functions. Hmm
