### ISSUE TITLE
internal/graphicsdriver: use uint32 indices when possible

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2612]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

On modern machines, uint32 is available for indices instead of uint16. Let's use uint32 whenever possible. This is a pure optimization without breaking compatibility.

### Why is this needed?

Uint32 would decrease draw calls by more batchings.

**Comment by hajimehoshi** [comment]
This requires an extension: https://developer.mozilla.org/en-US/docs/Web/API/OES_element_index_uint

**Comment by hajimehoshi** [comment]
As this seems a risky change, let me reset the milestone.

**Comment by hajimehoshi** [comment]
Now the internal uses []uint32. @SolarLune Do you think we need to have a []uint32 version of Draw*Triangles?

**Comment by SolarLune** [comment]
> Now the internal uses []uint32. @SolarLune Do you think we need to have a []uint32 version of Draw*Triangles?

I would probably just make the transition as quickly and suddenly as possible and just make the DrawTriangles functions take []uint32 instead immediately, rather than have multiple versions of functions and deprecating two of them. 

Deprecation is fine, but I feel like it can be confusing when the deprecated approach still exists right alongside the intended replacement for an extended period of time. It's also not as important in a language that takes advantage of modern version control systems (like Go), since you can simply target a version of a framework that has the functions you require at any time - if you upgrade and suddenly your code doesn't work, you can just roll back to a previous version of Ebitengine that had yet to replace deprecated functions.

If you are still in favor of deprecation and the existing DrawTriangles functions aren't hurting performance, then I guess I'd rather you hold off on adding []uint32 versions until some "breaking change version", like v3.0, I guess, without having to deprecate anything.

**Comment by hajimehoshi** [comment]
> If you are still in favor of deprecation and the existing DrawTriangles functions aren't hurting performance, then I guess I'd rather you hold off on adding []uint32 versions until some "breaking change version", like v3.0, I guess, without having to deprecate anything.

Yeah, I am in favor of deprecation over adding a breaking change. As []uint32 version is not so strongly on demand, I'll defer this change to v3 (#2829). I think v3 will be released in a few years. Thanks,

**Comment by hajimehoshi** [comment]
>  if you upgrade and suddenly your code doesn't work, you can just roll back to a previous version of Ebitengine that had yet to replace deprecated functions.

Things would not be so simple. If a thrid party library specifies a new Ebitengine version for its features, a user might not be able to downgread Ebitengine.
