### ISSUE TITLE
internal/atlas: overflow at `putImagesOnSourceBackend`

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2728]
### Ebitengine Version

e270dea4609542429f6c2f4148eeb79942376f7d

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.20.4 darwin/amd64

### What steps will reproduce the problem?

Add this test:

```go
func TestDestinationCountOverflow(t *testing.T) {
        const w, h = 256, 256
        src := atlas.NewImage(w, h, atlas.ImageTypeRegular)
        defer src.MarkDisposed()
        dst0 := atlas.NewImage(w, h, atlas.ImageTypeRegular)
        defer dst0.MarkDisposed()
        dst1 := atlas.NewImage(w, h, atlas.ImageTypeRegular)
        defer dst1.MarkDisposed()

        vs := quadVertices(w, h, 0, 0, 1)
        is := graphics.QuadIndices()
        dr := graphicsdriver.Region{
                X:      0,
                Y:      0,
                Width:  w,
                Height: h,
        }

        // Use dst0 as a destination for a while.
        for i := 0; i < 31; i++ {
                dst0.DrawTriangles([graphics.ShaderImageCount]*atlas.Image{src}, vs, is, graphicsdriver.BlendCopy, dr, graphicsdriver.Region{}, [graphics.ShaderImageCount - 1][2]float32{}, atlas.NearestFilterShader, nil, false)
                atlas.PutImagesOnSourceBackendForTesting(ui.GraphicsDriverForTesting())
        }

        // Use dst0 as a source for a while.
        // As dst0 is used as a destination too many times (31 is a maximum), dst0's backend should never be a source backend.
        for i := 0; i < 100; i++ {
                dst1.DrawTriangles([graphics.ShaderImageCount]*atlas.Image{dst0}, vs, is, graphicsdriver.BlendCopy, dr, graphicsdriver.Region{}, [graphics.ShaderImageCount - 1][2]float32{}, atlas.NearestFilterShader, nil, false)
                atlas.PutImagesOnSourceBackendForTesting(ui.GraphicsDriverForTesting())
                if dst0.IsOnSourceBackendForTesting() {
                        t.Errorf("dst0 cannot be on a source backend: %d", i)
                }
        }
}
```

and run this as a 32bit binary like

```sh
GOARCH=386 CGO_ENABLED=1 go test ./internal/atlas/
```

### What is the expected result?

The test succeeds

### What happens instead?

The test fails on 32bit machines. GOOS=wasm is treated as a 32bit machine.

### Anything else you feel useful to add?

This is already fixed ea1f596cdae9a3885aacdc6fa198af000226d810, but this should be backported to v2.5.

**Comment by hajimehoshi** [comment]
Hmm, this cannot be reproduced with 2.5 as the way a destination count is updated is much different (https://github.com/hajimehoshi/ebiten/issues/2676). So, I'll cherry-pick the fix, but without a test.

**Comment by hajimehoshi** [comment]
@quasilyte This might be the fix for your issue, if you were using 32bit machines or Wasm: https://github.com/hajimehoshi/ebiten/issues/2676#issuecomment-1650325027 Could you take a look at v2.5.7? Thanks,

**Comment by quasilyte** [comment]
I'm not using 32-bit myself, but I do make builds for Windows-32 for Steam.
As for the performance issues, I tried d9757138a7df31408d7bde0ebcfd179aca98e661 (the commit from `EDIT2`) on my Linux amd64 machine.
It feels like the hiccups are not as frequent now.

I still catch a single FPS drop when I load a big map and then it becomes smooth.
It looks like a freeze for ~5 frames (the average FPS and TPS are reported as ~30 after that).

I used a bit of `ColorM` hue rotations before, but now there are none. I only ever use a ColorScale.

I noticed that if I stop rendering (Draw()-ing) the background, the frame freeze goes away. The background is an image I create with NewImage, then I fill it with multiple DrawImage calls (it places the tiles on it). And then I Draw this big image as a background. The image size is 3392x3392 pixels. I do only render a subimage (the part that is inside the camera) instead of just moving the image when drawing. The camera size is 960x540, which is quite small.

**Comment by hajimehoshi** [comment]
I see. This means that the big image is used as a rendering destination once, and then used as a source for a while. In this case, Ebitengine tries to move the image's background (texture) from one for destinations to one for sources. This causes some draw calls, but I guessed this was not so heavy. I'll take a look further. Thank you!
