### ISSUE TITLE
text/v2: texts are not rendered with PixelMPlus12-Regular.ttf in a pixel-perfect way

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2955]
### Ebitengine Version

v2.7.0

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.22.2 darwin/arm64

### What steps will reproduce the problem?

Download `PixelMPlus12-Regular.ttf` from https://itouhiro.hatenablog.com/entry/20130602/font or https://github.com/itouhiro/PixelMplus/releases/download/v1.0.0/PixelMplus-20130602.zip, and run this program

```go
package main

import (
	"bytes"
	_ "embed"
	"log"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/text/v2"
)

//go:embed PixelMplus12-Regular.ttf
var font []byte

var faceSource *text.GoTextFaceSource

func init() {
	f, err := text.NewGoTextFaceSource(bytes.NewReader(font))
	if err != nil {
		panic(err)
	}
	faceSource = f
}

type Game struct{}

func (g *Game) Update() error {
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	text.Draw(screen, "Hello, 世界", &text.GoTextFace{
		Source: faceSource,
		Size:   12,
	}, nil)
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
	return 320, 240
}

func main() {
	if err := ebiten.RunGame(&Game{}); err != nil {
		log.Fatal(err)
	}
}
```

### What is the expected result?

The rendering result is pixel-perfect

### What happens instead?

The rendering result is not pixel-perfect

![image](https://github.com/hajimehoshi/ebiten/assets/16950/b1dff534-6d6b-4306-adaf-e702f6fb1d5d)

### Anything else you feel useful to add?

Reported by ぜのぺ https://twitter.com/xenopaper/status/1776293811884532015

Note that `PixelMPlus12-Regular.ttf` doesn't embed bitmap data.

**Comment by tinne26** [comment]
I made a silly mistake while testing with etxt earlier; I have been able to get pixel perfect output now. Using LayoutF with display scaling in order to obtain a full-sized screen, and then size 10 (or any integer multiple) at 72DPI should work on ebitengine too.

**Comment by hajimehoshi** [comment]
Hm? What would the actual code be?

**Comment by tinne26** [comment]
Here's a gist using ebitengine: https://gist.github.com/tinne26/d5b69378a04c2894d3469d3ecff755f7

**Comment by hajimehoshi** [comment]
Thanks. So,

```go
	scale := ebiten.DeviceScaleFactor()
	canvasWidth  := int(math.Ceil(float64(logicWinWidth )*scale))
	canvasHeight := int(math.Ceil(float64(logicWinHeight)*scale))
	return canvasWidth, canvasHeight
```

uses a high-resolution canvas (screen), and this is one of the solutions, but this would not work correctly when DeviceScaleFactor is 1, right? Also, this would affect all the other rendering logics unfortunately.

**Comment by tinne26** [comment]
This works correctly no matter what `DeviceScaleFactor` is, because you are scaling the logical size indicated by `Layout` in order to get the biggest possible screen in `Draw`, but when it comes to drawing text with the bitmap font, you should not be using `DeviceScaleFactor`, because you are typically rendering in a fixed-size canvas, and only later projecting to the screen.

Bitmap fonts are pixel art text. In the general case, pixel art assets can't be drawn sharply at an arbitrary resolution, only integer multiples. Now, there are specific scaling algorithms that work better with pixel art than linear scaling, and there are many specific tricks that you can apply to pixel art / bitmap fonts so they look sharper too, but that's too context dependent. If you have seen any library / game engine that does this in a more convincing way than ebitengine, we can look into what they do more specifically and try to recreate it, but that feels outside the scope of this issue, it's not like `text/v2` is not working correctly.

Of course, you could also work with the full screen for best resolution instead, finding out the scaling factor for your specific game/text and rendering at that higher resultion directly. This approach will always result in sharper text than "using a fixed-sized canvas and automatically scaling up with linear filtering". This is how we would draw vectorial fonts, in general, for best quality. There are some additional potential improvements, like gamma corrected font rendering, and specific tricks for bitmap fonts like the sharp rasterizer I made for etxt, but again, this feels outside the scope of the issue.

**Comment by hajimehoshi** [comment]
With the size 36px, the results is very close to pixel perfect, but not 100%.

![image](https://github.com/hajimehoshi/ebiten/assets/16950/10ddc835-516c-4ad9-87a9-f9c00e92d076)

**Comment by tinne26** [comment]
What code are you using though? On my code, you would have to change the 10 to 12 (line 54). I can grab the font later and test.

**Comment by hajimehoshi** [comment]
I'm using the code at https://github.com/hajimehoshi/ebiten/issues/2955#issue-2229812464

**Comment by tinne26** [comment]
I analized the glyphs of the 12px version of the font, and the problem is with the font. The EM size is 1000, which divided by 12 gets you 83.33333. That's already a bad enough, because you can't use decimal values in the font editor as far as I know, but I found that some distances are 83 and others are 84. I would blame the font in this case.

You could get font forge, open a glyph, select the ruler tool, measure by snapping to the vertices for the outlines.

**Comment by hajimehoshi** [comment]
OK that makes sense. I'm convinced that the font itself has a problem for this case.

Thank you for investigating that. I'll close this issue.
