### ISSUE TITLE
Keyboard support on iOS / android

### ISSUE THREAD

**Issue by joeblew99** [hajimehoshi/ebiten#362]
I think the only way to do this is to have our own keyboard rendered with OpenGL ?
QT in mobile I believe also has its own keyboard.
I am wondering your option since you have more experience.

**Comment by joeblew99** [comment]
Ah I was wrong about QT..
They are able to bring up the native keyboard on mobiles.
Whenever the user focuses in a text box it makes the call to open the native keyboard.
Should be pretty easy to see how it's done.

**Comment by hajimehoshi** [comment]
Duplicate with #237

There are two meaning of 'keyboard support' here.

1. Handling key press events
2. Supporting native input UI

For 1. #237 is the task. You would use an outside keyboard connected with bluetooth. From my experience, this feature is nice to have but not necessary.

For 2., as Ebiten supports `gomoible bind` instead of `gomobile build`, you can add them yourself. Ebiten doesn't have to support them directly.

Does this make sense?

**Comment by joeblew99** [comment]
thanks it does make sense. sorry about misunderstanding.

what you mean about supporting it myself at the objective c level ?

**Comment by hajimehoshi** [comment]
Yes, Objective-C or Java.

**Comment by joeblew99** [comment]
Got it - thanks for the clarification.

Will se how i go and get back to you..

**Comment by hajimehoshi** [comment]
:-)

**Comment by Inkeliz** [comment]
I think keyboard support is essential, even for games. Some stuff like "Player Name" is impossible without a software keyboard. 

I'm trying to implement that. It'll need to use JNI and some changes into the Java code. I don't know if it'll work. 

I'm also trying to create some `ebitenmobile build`. The goal is to take any extra `.java` and includes, similar to what Gio does (https://git.sr.ht/~eliasnaur/gio/tree/master/cmd/gogio/androidbuild.go#L226). It makes it possible to add external Java and call them using JNI, without the mess of using an external software directly (such as Android Studio).

**Comment by hajimehoshi** [comment]
Which case are you talking about?

1. Handling key press events
2. Supporting native input UI like text boxes

1. is already implemented anyway. Probably 2?

**Comment by Inkeliz** [comment]
Yes, I'm talking about #2, _I guess_. I'm not talking about EditText Widget, but the keyboard (the keyboard that appears when you _usually_ touch in some text field).

I don't know if makes sense the distinction between the native keyboard and the native input. But, I'm talking about only the keyboard, so you still need to get the text and display that text in somehow. 

Let's suppose that I need some "Player Name". I can create some pseudo text-box (draw anything using Ebiten). When it gets clicked: I call some `Typing()`. The `Typing()` will pop-up the keyboard on Android (potentially on _iOS_ and _Windows Tablet-Mode_). Also, some function will return the character (including backspace and special-characters), rather than each press-events.

**Comment by hajimehoshi** [comment]
Yeah, I understand the importance of native text fields.

Actually I was trying to create a cross platform text field with Ebiten (https://github.com/hajimehoshi/ebitenguidemo, which works only on Wasm so far). Probably this might be a huge project and would be separate from Ebiten core. I don't know.

I'm not sure we should have API like `Typing()`. Just having a native text field, and getting/setting a text from the field sounds enough.

Let's file a new issue to support native text fields not only on mobiles but also any environments.

**Comment by hajimehoshi** [comment]
>  I'm not talking about EditText Widget, but the keyboard (the keyboard that appears when you usually touch in some text field).

Well, if we can make a transparent text field, we can achieve what you want. Is that correct?

**Comment by Inkeliz** [comment]
> Well, if we can make a transparent text field, we can achieve what you want. Is that correct?

Yes, if there's a way to get the content from that invisible text field.

The `Typing()` thing, is to pop-up the keyboard. Even with some invisible-keyboard need to have some way to tell: "I need the user to enter an text now". Otherwise the keyboard will be displayed all time, which is not good. Suppose that you click in "Change Name", the keyboard will appear. After click "Save" it must close.

**Comment by hajimehoshi** [comment]
API to focus on a text field makes sense. Let's continue to discuss at https://github.com/hajimehoshi/ebiten/issues/1029
