### ISSUE TITLE
affine: GeoM.Invert functions

### ISSUE THREAD

**Issue by Shnifer** [hajimehoshi/ebiten#547]
Is it possible to reverse GeoM.Apply method, for example to get world coords from Camera.GeoM and MouseClick position? Or get reverse GeoM matrix

**Comment by hajimehoshi** [comment]
Sure. Probably I'll add `Invert` function for `GeoM` and `ColorM`.

**Comment by hajimehoshi** [comment]
Added `(*GeoM).Invert` and `(*GeoM).IsInvertible`. Note that `Invert` function affects the receiver (the caller of the method) and returns nothing. So if you want to keep the original `GeoM` instance, you need to copy like this:

```go
g := GeoM{}
g.Rotate(0.1234)
g.Translate(5, 6)
// ...
invG := g
invG.Invert()
invG.Apply(7, 8) // This works like g.UnApply(7, 8) you suggested.
```

**Comment by hajimehoshi** [comment]
Let me close this. Feel free to reopen this if you find any problems.

**Comment by Shnifer** [comment]
Thanks a lot, i will test it this week. A few questions:
1) is there a way to ask you a question other than here?
2) is there a maximum size of sprite sheet? How should i organize sprites for optimal performance and reliability?
3) perfomance tips talk about successive Draw calls. So will it be effective to sort "drawRequestQueue" by source image before calls execution?
4) if I draw an image outside of window borders, will it actually calls internally draw method? I have a lot of objects (galaxy of stars), with a dozen of them on screen simultaniously. Should I check for clipping or it is already in package?

**Comment by hajimehoshi** [comment]
1. #ebiten channel in Gophers Slack https://invite.slack.golangbridge.org/
2. The maximum size depends on devices. At least, 4096 should be fine (My old ZenFone's max texture size is 4096). If you can ignore portability, you can make textures up to maximum size on your device. You can check http://webglreport.com/ on your device. Basically you don't have to care about how to optimize textures since Ebiten automatically creates texture atlas (a.k.a. shared textures), but if you need, you can create an empty big image and use it as a texture atlas.
3. Basically yes, but in most cases the source texture of images are same by Ebiten's automatic shard textures. You might not need to do it, but it is not 100%. I'd recommend to test the performance without sorting and consider it only after you find the performance is not good.
4. Yeah, rendering outside of the destination doesn't do anything (see https://github.com/hajimehoshi/ebiten/blob/master/internal/restorable/vertices.go#L47).

**Comment by Shnifer** [comment]
Just a small misprint:

func (g *GeoM) det() float64 {
	if g == nil {
		return 1
	}
	return (g.a_1+1)*(g.d_1+1) - g.b * g.c
}

**Comment by hajimehoshi** [comment]
What do you think is the misprint?

**Comment by Shnifer** [comment]
(g.a_1+1)*(g.d_1+1) - g.b * g.c seems correct
(g.a_1+1)*(g.d_1+1) - g.b - g.c do not

**Comment by hajimehoshi** [comment]
Oops, thank you!
