### ISSUE TITLE
Tests times out on TravisCI

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#575]
The result is flaky. This sometimes succeeds, sometimes not.

https://travis-ci.org/hajimehoshi/ebiten/builds/362431262

Probably restorable/shareable package tests are problematic?

**Comment by Noofbiz** [comment]
Yeah, it depends on how many other tests are also running at the same time, since all the open source projects share resources on Travis CI. Some nights are especially bad. Also, since gomobile changed to building the stand alone toolchains I've found that you run out of disk space when running gomobile init on there, too

**Comment by hajimehoshi** [comment]
Yeah, but Ebiten's case is a little different: the stuck point is always same. I suspect there is a potential deadlock in Ebiten.

**Comment by hajimehoshi** [comment]
On second thought, each package tests run in a different process so deadlock should not happen. I guess there is something wrong in TravisCI itself...

**Comment by hajimehoshi** [comment]
It looks like just one empty test causes the deadlock..??

https://github.com/hajimehoshi/ebiten/blob/5399039b1f020261a734a0bc4ce5510c07037c6e/internal/shareable/shareable_test.go

**Comment by hajimehoshi** [comment]
Current idea: now there are three main routines in Ebiten tests, and it looks like TravisCI often freezes when the multiple main routines run at the same time. How about making them exclusive by using file lock?
