### ISSUE TITLE
Memory Spikes

### ISSUE THREAD

**Issue by wasedaigo** [hajimehoshi/ebiten#592]
After this change, XCode profiler started to show spikes of memory usage for ebiten built with go bind

https://github.com/hajimehoshi/ebiten/commit/7b5ad46e490cea7a969e013f4e3e790ab7ac2256

<img width="710" alt="screen shot 2018-04-28 at 11 34 52 pm" src="https://user-images.githubusercontent.com/182612/39398065-4ed1542c-4b43-11e8-8b44-99cad87e1d25.png">

**Comment by hajimehoshi** [comment]
Nice catch

**Comment by wasedaigo** [comment]
I double checked. I am 100% sure this commit is the cause..

**Comment by wasedaigo** [comment]
I removed "Leak" part. I am not sure about the leaks yet

**Comment by wasedaigo** [comment]
https://github.com/hajimehoshi/ebiten/commit/7b5ad46e490cea7a969e013f4e3e790ab7ac2256#diff-d76fb80ef37c2ffcc1d39de49f5bbd42R192

Commenting out this line fixed the spikes. The funny thing is, this line was not even called once at runtime. It should be gomobile problem... but I do not know what is the right way to fix this

**Comment by wasedaigo** [comment]
One thing to note is, the spike shows up and disappears even before closing the message balloon. This looks as if i.DrawImage() commands require a memory space temporary

**Comment by hajimehoshi** [comment]
> Does that mean our game is keep disposing images which can be reused? As clear command is called very often.

Yes.

**Comment by hajimehoshi** [comment]
> a message balloon

Note that this is an object that uses an Ebiten image in our game.

What I found is that `Clear` causes `DrawImage`, which makes the image (shared texture image in this case) 'stale' state, which means the image needs to load pixel data from GPU at the end of the frame. I think that's why the memory is temporarily consumed. I committed https://github.com/hajimehoshi/ebiten/commit/45afb6db67e58f6c8892647683fbf0d682340eec, which avoids 'stale' state when possible.

**Comment by hajimehoshi** [comment]
We confirmed it's fixed :-)
