### ISSUE TITLE
audio: MP3 decode result includes a small gap at the begining

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#620]
https://web.archive.org/web/20180111173850/http://lame.sourceforge.net/tech-FAQ.txt

**Comment by hajimehoshi** [comment]
The situation is complicated. I don't think I can fix this easily.

http://mp3decoders.mp3-tech.org/decoders_lame.html

**Comment by hajimehoshi** [comment]
I no longer recommend MP3 for looped music.

**Comment by derat** [comment]
Hi! I'm aware that this issue is closed and that [go-mp3](https://github.com/hajimehoshi/go-mp3) is archived and that `audio/mp3` is going to be removed (#2625), but do you happen to remember what made this complicated? `go-mp3` is still nice to use since there are no other native Go MP3 decoders. :-)

I'm excluding the delay (start) and padding (end) samples as specified in my files' LAME headers, but I'm still hearing brief gaps between files that should be seamless. Is `audio/mp3` adding an additional number of empty start or end samples during decoding, and if so, do you happen to know how many it is?

I've experimented with the different delays listed at http://mp3decoders.mp3-tech.org/decoders_lame.html, but none of them seem to match up. From manual inspection of some files that report a delay of 576 samples (downloaded from [here](https://github.com/dalecurtis/llama-demo/tree/master/sintel)), I see about 1320-1360 zero samples at the beginning after decoding with `audio/mp3`.

**Comment by hajimehoshi** [comment]
I don't have bandwidth to maintain the mp3 decoder and/or review other people's requests and changes. You should be able to convert the audio source to Ogg/Vorbis without so much loss, so I recommend using Ogg/Vorbis.
