### ISSUE TITLE
graphics: Use float32 instead of float64 at GeoM/ColorM APIs

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#664]
Not determined yet...

**Comment by nanoslayer** [comment]
Hello,
I was wondering why you decided to stick with float64. Many games don't really require full 64-bit precision, and it can be a hassle to convert from float32 to float64.
Since Ebiten converts float64 to float32 under the hood anyway, wouldn't it be more performant to simply accept float32? This would also be consistent with the vector.Path API, which only accepts float32.

**Comment by hajimehoshi** [comment]
While vector.Path's float32 values are passed to the low layer directly, GeoM's values can be calculated (e.g., multiplying) and can include numerical errors during the calculation.
