### ISSUE TITLE
graphics: Repeating texture/image on DrawTriangles

### ISSUE THREAD

**Issue by etherealmachine** [hajimehoshi/ebiten#761]
Is it possible to add a filter that triggers something like GL_REPEAT in the shader? Specifically I'd like to create some custom sprite shapes with DrawTriangles and texture them with a repeating texture.

**Comment by hajimehoshi** [comment]
Hi, thank you for asking!

Now Ebiten doesn't have this feature, so let me think to implement this.

As Ebiten creates automatic texture atlas, I cannot use GL_REPEAT directly. Probably I'd need to write a shader program to emulate this.

**Comment by etherealmachine** [comment]
https://gaurav-dixitv.github.io/phaser/2017/07/27/texture-repeat.html has a good example. I think you're right that you'd need to modify the shader, I looked at it but it was a bit out of my depth. I think something like sampling the texture pixels modulo image width/height might work, not sure how hard that would be though.

**Comment by hajimehoshi** [comment]
I'm convinced that the tiling rendering would be useful. I'll embed the image rectangle info into vertices and, yes, emulate repeating texels by modulo calculation. I'd need to measure performance change (regression, maybe?) caused by adding extra data to vertices. I hope this change would not affect the performance very much.

**Comment by hajimehoshi** [comment]
Implemented. Note that I might rename the type `Address` later.
