### ISSUE TITLE
Consider making IsKeyJustPressed and IsKeyJustReleased variadic

### ISSUE THREAD

**Issue by peterhellberg** [hajimehoshi/ebiten#770]
> (As discussed in the #gamedev channel on Slack)

How about making the `IsKeyJust*` functions variadic?

This would allow:

```go
inpututil.IsKeyJustPressed(ebiten.KeyEscape) || inpututil.IsKeyJustPressed(ebiten.KeyQ)
```

to be written as:

```go
inpututil.IsKeyJustPressed(ebiten.KeyEscape, ebiten.KeyQ)
```

This would however make the naming a little bit off.

@Noxer then suggested: 

```go
inpututil.AnyKeyJustPressed(ebiten.KeyQ, ebiten.KeyX)
inpututil.AllKeysJustPressed(ebiten.KeyA, ebiten.KeyB)
```

I then raised the question of having a `inpututil.KeyJustPressed()` function that returns the just pressed key. (For use in a `switch`)

**Comment by hajimehoshi** [comment]
Thank you!

My current concern is that it might be confusing: does `IsKeyJustPressed(keyA,  keyB)` return true only when keyA and keyB are pressed, or when either keyA and keyB is pressed?

Thus I feel like introducing a new API with a new name would be better. Let me consider...

**Comment by peterhellberg** [comment]
Would it instead be possible to introduce a `ebiten.Input()` function that return all input, not just the printable runes? (Maybe this would surface too much of the internal implementation?)

**Comment by hajimehoshi** [comment]
I'm afraid moving `inpututil` functions to `ebiten` package is not my option as I'd like to keep `ebiten` package minimum.

**Comment by hajimehoshi** [comment]
Oops I was misunderstanding your request.

> Would it instead be possible to introduce a ebiten.Input() function that return all input, not just the printable runes as returned by ebiten.InputChars()?

I think this would be confusing. If upper case `A` is included in the result of `ebiten.InputChars`, should `ebiten.Input` include Shift key? Some mod keys wouldn't match with the concept of `InputChars` I guess.

**Comment by hajimehoshi** [comment]
I started to think that `ebiten.InputKeys` as a counterpart of `ebiten.InputChars` might work and be more consistent. I feel like there would be a good API design in the general inputting. Let me think...

**Comment by hajimehoshi** [comment]
The current main input APIs are:

* Keyboard
  * `IsKeyPressed`
  * `InputChars`
* Mouse
  * `IsMouseButtonPressed`
* Gamepad
  * `GamepadIDs`
  * `IsGamepadButtonPressed`
* Touch
  * `TouchIDs`

So probably adding `PressedKeys` would make sense? This API would not be exclusive with the other APIs in `ebiten` package, then I'd put this in `inpututil` package.

`PressedMouseButtons` would be useless (There are only three types of mouse buttons). `PressedGamepadButtons` would be useless maybe since the number of gamepad buttons can be obtained by `GamepadButtonNum`.
