### ISSUE TITLE
Investigate why JavaScript GC takes long time

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#944]
![Profiling result](https://i.gyazo.com/0defa7016a23a992b6214da2369ede7d.png)

This is a very typical profiling result (Ebiten's 'blocks' example). JS GC (not Go GC) is really problematic. Let's search for a solution.

**Comment by silbinarywolf** [comment]
One thing that might help that I've seen occur in Handmade Hero is that idea that you have a temporary storage allocator (also known as a bump allocator), where you have a fixed-size amount of bytes allocated at startup (8-16KB or so) then you allocate things from this pool of bytes however you want.

Then, on the next frame, you reset the allocator so that it starts allocating from the start of the byte array.

For a much clearer blog post on the concept, read this:
https://hacks.mozilla.org/2019/03/fast-bump-allocated-virtual-doms-with-rust-and-wasm/

**Comment by hajimehoshi** [comment]
It looks like this is no longer a problem. I have reduced allocations of ArrayBuffer, and I think this is why. 59333ba1adf065efcca4c706071de0094f6ce5d9

I'll revisit this if we find this problem again.

**Comment by hajimehoshi** [comment]
I found this happened again...

**Comment by hajimehoshi** [comment]
My current understanding is that finalizing js.Value object takes long. Unfortunately we cannot make them zero, but we can reduce them. Actually the situation seems better after #1426 was fixed.
